# Generated by Django 4.2.2 on 2023-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
